[Windows:children]
DomainControllers
WebServers

[DomainControllers]
prod-dc01
prod-dc02

[WebServers]
prod-web01
prod-web02

[Windows:vars]
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=credssp
ansible_user=Adatum\Administrator
ansible_password=Password1