all:
  children:
    AnsibleServers:
      localhost:
      vars:
        ansible_connection:local
        resourceGroupName:AnsibleTerraform
        resourceGroupLocation:EastUS
        storageAccountName:storageacc79ruds778
        virtualNetworkName:vmnetwork
        virtualNetworkAddressSpace:10.0.0.0/8
        virtualNetworkDnsServer1:10.0.0.11
        virtualNetworkDnsServer2:10.0.0.12
        subnetName:lan
        subnetNetworkID:10.0.0.0/24
        storageAccountTier:Standard
        storageAccountReplicationType:LRS
        dc1Size:Standard_DS1_v2
        dc1DiskCaching:ReadOnly
        dc1ManagedDiskType:Standard_LRS
        vmOffer:WindowsServerSemiAnnual
        vmSku:Datacenter-Core-1709-smalldisk
        vmUserName:AzureAdmin
        vmPassword:AzurePassword1
    Windows:
      children:
        DomainControllers:
          contdc01-azurevm.eastus.cloudapp.azure.com:
            vars:
              hostname:contdc01
              ipAddress:10.0.0.11
          contdc02-azurevm.eastus.cloudapp.azure.com:
        vars:
          resourceGroupName:AnsibleTerraform
          dc1Name:contdc01
          domain_name:contoso.com
          SafemodeAdministratorPassword_username:AzureAdmin
          SafemodeAdministratorPassword_password:AzurePassword1
          DomainAdministratorCredential_username:AzureAdmin
          DomainAdministratorCredential_password:AzurePassword1
        WebServers:
          contweb01-azurevm.eastus.cloudapp.azure.com:
          contweb02-azurevm.eastus.cloudapp.azure.com:
      vars:
        ansible_connection:winrm
        ansible_winrm_server_cert_validation:ignore
        ansible_winrm_transport:credssp
        ansible_user:Contoso\AzureAdmin
        ansible_password:AzurePassword1