- hosts: localhost
  gather_facts: no
  vars: 
    vmList: "{{ hostvars[item]['hostname'] }} = {{ hostvars[item]['ipAddress'] }}"
  with_items: "{{ groups['DomainControllers'] }}"
  roles:
    - azureInfrastructure

#- hosts: DomainControllers[0]
#  gather_facts: no
#  roles:
#  - firstDomainControllerConfiguration