- hosts: localhost
  gather_facts: no
  roles:
    - azureInfrastructure

- hosts: DomainControllers[0]
  gather_facts: yes
  roles:
  - newADDomain

- hosts: DomainControllers[1]
  gather_facts: yes
  roles:
  - newADDomainController