- hosts: localhost
  gather_facts: no
  tasks:

- name: Run dc1Infrastructure.yml to prepare infra for first DC
  import_playbook: roles/domainControllers/tasks/dc1Infrastructure.yml

#- hosts: DomainControllers[0]

  #- name: Run dc1Configuration.yml to prepare infra for first DC
  #  import_playbook: roles/common/tasks/dc1Configuration.yml