- hosts: localhost
  gather_facts: no
  tasks:
    - name: Import variables from vmPrerequisitesVars.yml
      include_vars:
        file: "../vars/vmDeploymentVars.yml"

    - name: Run terraform configuration
      terraform:
          project_path: "../files"
          state_file: "/var/lib/terraform/terraform.tfstate"
          variables:
            subscription_id: '{{ subscription_id }}' 
            client_id: '{{ client_id }}'
            tenant_id: '{{ tenant_id }}'
            client_secret: '{{ client_secret }}'
