- name: Wait for connection
  wait_for_connection:
    delay: 0
    timeout: 60
    
- name: Install PowerShell modules
  win_psmodule:
    name: '{{ item }}'
    state: present
  with_items:
    - xComputerManagement
    - xNetworking
    - xWebAdministration

- name: Set WinRM service to automatic
  win_dsc:
    resource_name: Service
    Name: WinRM
    StartupType: Automatic

- name: Install Windows Features
  win_feature:
    name: Web-Server
    state: present

- name: Join to the domain
  win_dsc:
    resource_name: xComputer
    Name: '{{ hostname }}'
    DomainName: '{{ domain_name }}'
    Credential_username: '{{ DomainAdministratorCredential_username }}'
    Credential_password: '{{ DomainAdministratorCredential_password }}'
  register: JoinDomain

- name: Restart virtual machine
  azure_rm_virtualmachine:
    resource_group: '{{ resourceGroupName }}'
    name: '{{ hostname }}'
    client_id: '{{ client_id }}'
    subscription_id: '{{ subscription_id }}'
    tenant: '{{ tenant_id }}'
    secret: '{{ client_secret }}'
    restarted: yes
  when: JoinDomain.reboot_required == True
  delegate_to: localhost    

- name: Wait for reboot
  wait_for_connection:
    delay: 120
    timeout: 600
  when: JoinDomain.reboot_required == True
